### ISSUE TITLE
MemberRepository 구조 변경 후 스프링 빈 순환 참조 이슈 발생

### ISSUE THREAD

**Issue by jaejeong1** [f-lab-edu/ticket-seller#6]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memberRepositoryImpl' defined in file [/Users/jaejeongjang/Workspace/ticket-seller/out/production/classes/com/jj/ticketseller/repository/MemberRepositoryImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'memberRepositoryImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.3.jar:6.0.3]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.3.jar:6.0.3]

MemberRepositoryImpl 선언부
![image](https://user-images.githubusercontent.com/89735640/215305662-e2bdba4a-254e-4e42-873f-747d80fc0dc7.png)

**Comment by heeve1** [comment]
흠 요것 PR의 댓글로 인해 작업하시다가 에러가 발생하신것 같군요. 
전체 클래스를 보지 못해 애매하지만
MemberCustomRepository interface - 원하는 메소드만 있는 인터페이스
MemberRepositoryImpl -  위 MemberCustomRepository interface를 구현하는 클래스(바로 위 스샷)
이라고 할 때, 생성자로 주입받을 클래스는 MemberCustomRepository가 아닌 MemberRepository(JpaRepository)여야 할겁니다~

**Comment by jaejeong1** [comment]
#4 PR에서 말씀주신 부분이 정확히 이해되지 않은 상태에서 구현되어 발생한 문제였습니다. JpaRepository를 구현한 후 MemberRepository에 있던 기존 API들(save, findOne 등..)을 추가로 구현해주니 해결되었습니다. 감사합니다.
